KafkaEventSubscriber: Fix FloggerFormatString pattern flagged by error prone
Build is failing with recent Error Prone version:

  KafkaEventSubscriber.java:153: error: [FloggerFormatString]
  missing argument for format specifier '%s'
                  logger.atSevere().withCause(e).log(
                                                    ^
    (see https://errorprone.info/bugpattern/FloggerFormatString)

Change-Id: Ib3b8ec6c6d5d63ec7a8f74888768375766f43d52